[package]
name = "relay-hosts"
version = "0.1.45"
edition = "2024"

[dependencies]
bytes = "1"
chrono = { version = "0.4", features = ["serde"] }
axum = { workspace = true, features = ["ws"] }
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
futures-util = "0.3"
http = "1"
relay-client = { path = "../relay-client" , version = "0.1.45" }
relay-ws = { path = "../relay-ws" , version = "0.1.45" }
relay-control = { path = "../relay-control" , version = "0.1.45" }
remote-info = { path = "../remote-info" , version = "0.1.45" }
relay-types = { path = "../relay-types" , version = "0.1.45" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
services = { path = "../services" , version = "0.1.45" }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = "0.26"
tracing = { workspace = true }
trusted-key-auth = { path = "../trusted-key-auth" , version = "0.1.45" }
url = "2.5"
utils = { path = "../utils" , version = "0.1.45" }
uuid = { version = "1.0", features = ["v4", "serde"] }
relay-webrtc = { path = "../relay-webrtc" , version = "0.1.45" }
ws-bridge = { path = "../ws-bridge" , version = "0.1.45" }
tokio-util = { version = "0.7", features = ["rt"] }
base64 = "0.22"
